name: Generate Snake Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *" # every 24h
  workflow_dispatch: # manual trigger
  push:
    branches:
      - main

env:
  OUT_DIR: dist/contributions-snake
  GIT_USER_NAME: github-actions[bot]
  GIT_USER_EMAIL: github-actions[bot]@users.noreply.github.com

jobs:
  generate:
    name: Generate snake
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1
      
      - name: Generate svg
        uses: Platane/snk@v3.4.1
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            ${{ env.OUT_DIR }}/light.svg
            ${{ env.OUT_DIR }}/dark.svg??palette=github-dark

      - name: Configure git user
        run: |
          git config user.name "${{ env.GIT_USER_NAME }}"
          git config user.email "${{ env.GIT_USER_EMAIL }}"
      
      - name: Push changes
        run: |
          git add ${{ env.OUT_DIR }}/*
          git commit -m "action: github contributions snake $(date '+%Y-%m-%d %H:%M:%S')"
          git push
