name: Generate Snake Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *" # every 24h
  workflow_dispatch: # manual trigger
  push:
    branches:
      - main

env:
  OUT_FILE_SVG: dist/contributions-snake.svg

jobs:
  generate:
    name: Generate snake
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1
      
      - name: Generate svg
        uses: Platane/snk@v3.4.1
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            ${{ env.OUT_FILE_SVG }}
      
      - name: Push changes
        run: |
          git add ${{ env.OUT_FILE_SVG }}
          git commit -m "action: github contributions snake $(date '+%Y-%m-%d %H:%M:%S')"
          git push
